# Generated by Django 4.0.5 on 2022-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_replacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(default='img/default.jpg', upload_to='combo/')),
                ('price', models.IntegerField()),
                ('items', models.ManyToManyField(related_name='combo', to='capstone.replacement')),
            ],
        ),
    ]
