# Generated by Django 4.0.5 on 2022-06-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_voucher_remove_item_category_item_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_name',
        ),
    ]
