# Generated by Django 4.0.5 on 2022-06-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='capstone.category')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default/default.jpg', upload_to='dishes/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='replacements',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='Replacement',
        ),
        migrations.AddField(
            model_name='dish',
            name='dessert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessertDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dessert_replacers',
            field=models.ManyToManyField(related_name='dessertReplacerDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fried',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friedDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fried_replacers',
            field=models.ManyToManyField(related_name='friedReplacerDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='pasta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastaDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='pasta_replacers',
            field=models.ManyToManyField(related_name='pastaReplacerDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ManyToManyField(related_name='dishes', to='capstone.picture'),
        ),
        migrations.AddField(
            model_name='dish',
            name='snack',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snackDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='dish',
            name='snack_replacers',
            field=models.ManyToManyField(related_name='snackReplacerDishes', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(related_name='orders', to='capstone.dish'),
        ),
    ]
