# Generated by Django 4.0.5 on 2022-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dessert_replacers',
            field=models.ManyToManyField(blank=True, related_name='dessertReplacerDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fried_replacers',
            field=models.ManyToManyField(blank=True, related_name='friedReplacerDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='pasta_replacers',
            field=models.ManyToManyField(blank=True, related_name='pastaReplacerDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='snack_replacers',
            field=models.ManyToManyField(blank=True, related_name='snackReplacerDishes', to='capstone.item'),
        ),
    ]
