# Generated by Django 4.0.5 on 2022-06-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_alter_dish_picture_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessertDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fried',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friedDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastaDishes', to='capstone.item'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snackDishes', to='capstone.item'),
        ),
    ]
