# Generated by Django 4.0.5 on 2022-06-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_alter_dish_dessert_alter_dish_fried_alter_dish_pasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dessert_replacers',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fried',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fried_replacers',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='pasta_replacers',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='snack',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='snack_replacers',
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='dishItems', to='capstone.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='capstone.category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='capstone.category'),
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacedItem', to='capstone.item')),
                ('replacers', models.ManyToManyField(blank=True, related_name='replacers', to='capstone.item')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='replacers',
            field=models.ManyToManyField(blank=True, related_name='dishReplacers', to='capstone.replacement'),
        ),
    ]
