# Generated by Django 4.0.5 on 2022-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_remove_dish_dessert_remove_dish_dessert_replacers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
