# Generated by Django 4.0.5 on 2022-06-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0015_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('choices', models.ManyToManyField(blank=True, related_name='choices', to='capstone.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacedItem', to='capstone.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='replacers',
        ),
        migrations.DeleteModel(
            name='Replacement',
        ),
        migrations.AddField(
            model_name='dish',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='dishChoices', to='capstone.selection'),
        ),
    ]
