# Generated by Django 4.0.5 on 2022-06-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0016_selection_remove_dish_replacers_delete_replacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
