# Generated by Django 4.0.5 on 2022-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0017_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
