# Generated by Django 4.0.5 on 2022-06-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0018_remove_category_type_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
