# Generated by Django 4.0.5 on 2022-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_remove_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/imagenotfound.png', upload_to='singleItemsCategory/'),
        ),
    ]
