# Generated by Django 4.0.5 on 2022-06-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0020_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='picture',
            new_name='image',
        ),
        migrations.CreateModel(
            name='ComboItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comboItems', to='capstone.category')),
            ],
        ),
    ]
