# Generated by Django 4.0.5 on 2022-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0022_rename_image_dish_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='choices',
        ),
        migrations.AddField(
            model_name='dish',
            name='selections',
            field=models.ManyToManyField(blank=True, related_name='dishSelections', to='capstone.selection'),
        ),
    ]
