# Generated by Django 4.0.5 on 2022-07-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0025_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
