# Generated by Django 4.0.5 on 2022-07-12 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0027_deal_delete_comboitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
