# Generated by Django 4.0.5 on 2022-07-12 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0028_deal_end_deal_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='hashtag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
