# Generated by Django 4.0.5 on 2022-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0029_deal_hashtag_alter_deal_end_alter_deal_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='hashtag',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
