# Generated by Django 4.0.5 on 2022-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0030_alter_deal_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(default='default/imagenotfound.png', upload_to='deals/'),
        ),
    ]
