# Generated by Django 4.0.5 on 2022-07-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0032_deal_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': [-1]},
        ),
    ]
