# Generated by Django 4.0.5 on 2022-07-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0033_alter_picture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='item',
            new_name='default',
        ),
    ]
