# Generated by Django 4.0.5 on 2022-07-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0034_alter_item_options_alter_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={},
        ),
    ]
