# Generated by Django 4.0.5 on 2022-07-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0035_alter_selection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
