# Generated by Django 4.0.5 on 2022-07-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0037_rename_dish_order_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='capstone.dish'),
        ),
    ]
