# Generated by Django 4.0.5 on 2022-07-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0038_rename_cost_order_price_remove_order_dishes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
