# Generated by Django 4.0.5 on 2022-07-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0039_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
