# Generated by Django 4.0.5 on 2022-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0040_order_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.FloatField(),
        ),
    ]
