# Generated by Django 4.0.5 on 2022-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0041_alter_voucher_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='initial_price',
        ),
    ]
