# Generated by Django 4.0.5 on 2022-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0042_remove_order_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.JSONField(null=True),
        ),
    ]
