# Generated by Django 4.0.5 on 2022-07-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0043_order_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
    ]
