# Generated by Django 4.1.4 on 2022-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
