# Generated by Django 4.1.4 on 2022-12-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfc', '0002_category_image_url_deal_image_url_dish_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
